server:
  port: 9002

spring:
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.64.140
    port: 6379
  datasource:
#      有的mysql如5.0 下面必须改成com.mysql.jdbc.Driver
        driver-class-name: com.mysql.cj.jdbc.Driver        
        url: jdbc:mysql://192.168.64.140:3306/waiwaimall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
        username: root        
        password: 'root'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  file:
    path: ./logs
  level:
    com.tedu: debug
SavePath:
  ProfilePhoto: 'W\upload\'  #图标存储路径
  ProfilePhotoMapper: '/upload/'  #图标的映射路径

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
